- name: system | auto-provision | create user ansible
  user:
    name: ansible
    system: yes
    
- name: system | auto-provision | add ansible to fcron.allow
  lineinfile:
    path: /etc/fcron/fcron.allow
    line: ansible

- name: system | auto-provision | add cron job
  cron:
    cron_file: 
    name: ansible auto-provision
    user: ansible
    minute: "*/10"
    job: ansible-pull --only-if-changed --url https://github.com/ito-rafael/pc-general-config.git ansible/local.yml   
