- name: users | rafael | create group
  group:
    name: rafael
    state: present

- name: users | rafael | create user
  user:
    name: rafael
    group: rafael
    groups: {{ sudo_group }}
    state: present
    comment: "Rafael Ito"
    password: "{{ rafael_passwd }}"
    shell: /usr/bin/zsh

- name: users | rafael | add sudoers file
  copy:
    src: users/sudoers_rafael
    dest: /etc/sudoers.d/rafael
    owner: root
    group: root
    mode: 0440
